version: "2.2"

services:
  nginx:
    image: ${COMPOSE_PROJECT_NAME}-nginx
    build:
      context: docker/nginx
    init: true
    network_mode: "host"
    volumes:
      - ./docker/nginx/nginx.conf:/nginx.conf
      - ./docker/example-certificates/server/certificate.crt:/certificate.crt
      - ./docker/example-certificates/server/certificate.key:/certificate.key
      - ./docker/example-certificates/client/rootca.crt:/trusted_root.crt
    working_dir: /examples
    command: ["nginx", "-c", "/nginx.conf"]

  server:
    image: ${COMPOSE_PROJECT_NAME}-python
    build:
      context: docker/python
    init: true
    network_mode: "host"
    volumes:
      - ./aiowstunnel:/pypackages/aiowstunnel
      - ./examples:/examples
    working_dir: /examples
    command: ["python", "server.py"]
    environment:
      PYTHONPATH: /pypackages

  client:
    image: ${COMPOSE_PROJECT_NAME}-python
    build:
      context: docker/python
    init: true
    network_mode: "host"
    volumes:
      - ./aiowstunnel:/pypackages/aiowstunnel
      - ./examples:/examples
      - ./docker/example-certificates/client/certificate.crt:/certificate.crt
      - ./docker/example-certificates/client/certificate.key:/certificate.key
      - ./docker/example-certificates/server/rootca.crt:/trusted_root.crt
    working_dir: /examples
    command: ["python", "client.py"]
    environment:
      PYTHONPATH: /pypackages
