version: "2.2"

services:
  nginx:
    image: ${COMPOSE_PROJECT_NAME}-nginx
    build:
      context: docker/nginx
    init: true
    network_mode: "host"
    volumes:
      - ./docker/nginx/nginx.conf:/nginx.conf
      - ./docker/nginx/nginx_mime.types:/nginx_mime.types
      - ./examples/certificates:/certificates
      - ./aiowstunnel/healthcheck_frontend/build:/www-root
    working_dir: /examples
    command: ["nginx", "-c", "/nginx.conf"]

  server:
    image: ${COMPOSE_PROJECT_NAME}-python
    build:
      context: docker/python
    init: true
    network_mode: "host"
    stop_signal: SIGINT
    volumes:
      - ./aiowstunnel:/pypackages/aiowstunnel
      - ./examples:/examples
    working_dir: /examples
    command: ["python", "server.py"]
    environment:
      PYTHONPATH: /pypackages

  client:
    image: ${COMPOSE_PROJECT_NAME}-python
    build:
      context: docker/python
    init: true
    network_mode: "host"
    stop_signal: SIGINT
    volumes:
      - ./aiowstunnel:/pypackages/aiowstunnel
      - ./examples:/examples
      # - ./docker/example-certificates/client/certificate.crt:/certificate.crt
      # - ./docker/example-certificates/client/certificate.key:/certificate.key
      # - ./docker/example-certificates/server/rootca.crt:/trusted_root.crt
    working_dir: /examples
    command: ["python", "client.py"]
    environment:
      PYTHONPATH: /pypackages

  appserver:
    image: ${COMPOSE_PROJECT_NAME}-python
    build:
      context: docker/python
    init: true
    network_mode: "host"
    stop_signal: SIGINT
    volumes:
      - ./aiowstunnel:/pypackages/aiowstunnel
      - ./examples:/examples
    working_dir: /examples
    command: ["python", "appserver.py"]
    environment:
      PYTHONPATH: /pypackages

  pypi:
    image: ${COMPOSE_PROJECT_NAME}-python-pypi
    build:
      context: docker/python
      dockerfile: Dockerfile-pypi
    init: true
    network_mode: "host"
    stop_signal: SIGINT
    volumes:
      - ./examples:/examples
    working_dir: /examples

  react:
    image: ${COMPOSE_PROJECT_NAME}-react
    build:
      context: docker/react
    init: true
    network_mode: "host"
    volumes:
      - ./aiowstunnel/healthcheck_frontend:/frontend
    user: 1000:1000
    working_dir: /frontend
